# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    public class Addition {

	public static void main(String[] args) {
		int a=10;
		int b=20;
		int e;
		e=a+b;
		System.out.println("c value is"+e) ;

	}

}

  displayName: 'Run a multi-line script'
